# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'routePlanner.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1194, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startStationEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.startStationEntry.setGeometry(QtCore.QRect(90, 230, 191, 41))
        self.startStationEntry.setObjectName("startStationEntry")
        self.startTextBox = QtWidgets.QLabel(self.centralwidget)
        self.startTextBox.setGeometry(QtCore.QRect(160, 160, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.startTextBox.setFont(font)
        self.startTextBox.setObjectName("startTextBox")
        self.destinationTextBox = QtWidgets.QLabel(self.centralwidget)
        self.destinationTextBox.setGeometry(QtCore.QRect(20, 300, 271, 61))
        self.destinationTextBox.setObjectName("destinationTextBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -80, 1201, 881))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("backdrop.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.destinationStationEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.destinationStationEntry.setGeometry(QtCore.QRect(90, 350, 191, 41))
        self.destinationStationEntry.setObjectName("destinationStationEntry")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(760, 190, 271, 81))
        self.label_2.setObjectName("label_2")
        self.s = QtWidgets.QTextBrowser(self.centralwidget)
        self.s.setGeometry(QtCore.QRect(760, 250, 301, 131))
        self.s.setObjectName("s")
        self.tubeMapPopUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.tubeMapPopUpButton.setGeometry(QtCore.QRect(80, 600, 181, 101))
        self.tubeMapPopUpButton.setObjectName("tubeMapPopUpButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(880, 10, 301, 181))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("facemask.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 60, 471, 71))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(720, 630, 321, 81))
        self.label_5.setObjectName("label_5")
        self.findRouteButton = QtWidgets.QPushButton(self.centralwidget)
        self.findRouteButton.setGeometry(QtCore.QRect(90, 450, 201, 41))
        self.findRouteButton.setObjectName("findRouteButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(330, 220, 391, 421))
        self.textEdit.setObjectName("textEdit")
        self.ETA_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.ETA_edit.setGeometry(QtCore.QRect(820, 650, 151, 41))
        self.ETA_edit.setObjectName("ETA_edit")
        self.label.raise_()
        self.startStationEntry.raise_()
        self.startTextBox.raise_()
        self.destinationTextBox.raise_()
        self.destinationStationEntry.raise_()
        self.label_2.raise_()
        self.s.raise_()
        self.tubeMapPopUpButton.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.findRouteButton.raise_()
        self.textEdit.raise_()
        self.ETA_edit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startTextBox.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#000000;\">Start:</span></p></body></html>"))
        self.destinationTextBox.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">Destination:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Journey Summary</span></p></body></html>"))
        self.tubeMapPopUpButton.setText(_translate("MainWindow", "Click Here for Tube Map"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; text-decoration: underline;\">Tube Route Planner</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">ETA: </span></p></body></html>"))
        self.findRouteButton.setText(_translate("MainWindow", "Find Route"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
